version: '3.7'

services:
  app:
    container_name: django_app
    build:
      context: ./djbot
    volumes:
      - ./djbot:/app
    env_file:
      - .env
    networks:
      - my_network
    depends_on:
      - db

  nginx:
    container_name: nginx
    restart: unless-stopped
    build:
      context: nginx
    ports:
      - "80:80"
    networks:
      - my_network
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER:-user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
      - POSTGRES_DB=${DB_NAME:-db_name}
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my_network

networks:
  my_network:
    driver: bridge