# Generated by Django 4.0.4 on 2022-04-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_user_profile_options_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='external_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='Внешний ID пользователя'),
        ),
    ]
