# Generated by Django 4.0.4 on 2022-04-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='about',
            field=models.TextField(null=True, verbose_name='О пользователе'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='main_game',
            field=models.TextField(null=True, verbose_name='Основная игра'),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='steam_nickname',
            field=models.TextField(null=True, verbose_name='Никнейм в Steam'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='name',
            field=models.TextField(null=True, verbose_name='Имя пользователя'),
        ),
    ]
