# Generated by Django 4.0.4 on 2022-04-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_profile_about_user_profile_main_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='in_search',
            field=models.BooleanField(null=True, verbose_name='Статус в поиске'),
        ),
    ]
