# Generated by Django 5.1.4 on 2024-12-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="gamename",
            field=models.TextField(unique=True, verbose_name="Название игры"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="main_game",
            field=models.TextField(verbose_name="Основная игра"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="name",
            field=models.TextField(verbose_name="Имя пользователя"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="steam_nickname",
            field=models.TextField(verbose_name="Никнейм в Steam"),
        ),
    ]
